server:
  port: 2003
eureka:
  client:
    service-url:
      defaultZone: http://192.168.254.136:1111/eureka/
spring:
  application:
    name: ribbon-consumer

management:
  endpoints:
    web:
      exposure:
        include: "*"